# Generated by Django 3.1.1 on 2020-09-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitteruser',
            old_name='followed',
            new_name='following',
        ),
    ]
